package com.zzu.bbs.model;

public class Posting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.id
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.title
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.gmt_create
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.gmt_modify
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Long gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.creator
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.comment_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.view_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.like_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.dislike_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Integer dislikeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.tag
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.sticky
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private Integer sticky;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column posting.description
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.id
     *
     * @return the value of posting.id
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.id
     *
     * @param id the value for posting.id
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.title
     *
     * @return the value of posting.title
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.title
     *
     * @param title the value for posting.title
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.gmt_create
     *
     * @return the value of posting.gmt_create
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.gmt_create
     *
     * @param gmtCreate the value for posting.gmt_create
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.gmt_modify
     *
     * @return the value of posting.gmt_modify
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.gmt_modify
     *
     * @param gmtModify the value for posting.gmt_modify
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.creator
     *
     * @return the value of posting.creator
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.creator
     *
     * @param creator the value for posting.creator
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.comment_count
     *
     * @return the value of posting.comment_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.comment_count
     *
     * @param commentCount the value for posting.comment_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.view_count
     *
     * @return the value of posting.view_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.view_count
     *
     * @param viewCount the value for posting.view_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.like_count
     *
     * @return the value of posting.like_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.like_count
     *
     * @param likeCount the value for posting.like_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.dislike_count
     *
     * @return the value of posting.dislike_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Integer getDislikeCount() {
        return dislikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.dislike_count
     *
     * @param dislikeCount the value for posting.dislike_count
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setDislikeCount(Integer dislikeCount) {
        this.dislikeCount = dislikeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.tag
     *
     * @return the value of posting.tag
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.tag
     *
     * @param tag the value for posting.tag
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.sticky
     *
     * @return the value of posting.sticky
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public Integer getSticky() {
        return sticky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.sticky
     *
     * @param sticky the value for posting.sticky
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setSticky(Integer sticky) {
        this.sticky = sticky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column posting.description
     *
     * @return the value of posting.description
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column posting.description
     *
     * @param description the value for posting.description
     *
     * @mbggenerated Sun May 16 23:40:03 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}